-- Table: public.gbif_csp_20220320_clipped_foa_taxonomy

--DROP TABLE IF EXISTS public.gbif_csp_20220320_clipped_foa_taxonomy;

CREATE TABLE IF NOT EXISTS public.gbif_csp_20220320_clipped_foa_taxonomy
(
    objectid integer,
gbifid bigint NOT NULL,
accessrights text,
bibliographiccitation text,
identifier text,
language text,
license text,
modified text,
reference text,
rights text,
rightsholder text,
type text,
institutionid text,
collectionid text,
datasetid text,
institutioncode text,
collectioncode text,
datasetname text,
ownerinstitutioncode text,
basisofrecord text,
informationwithheld text,
dynamicproperties text,
occurrenceid text,
catalognumber text,
recordnumber text,
recordedby text,
individualcount text,
reproductivecondition text,
occurrencestatus text,
preparations text,
disposition text,
associatedreferences text,
associatedtaxa text,
othercatalognumbers text,
occurrenceremarks text,
organismid text,
previousidentifications text,
materialsampleid text,
eventid text,
fieldnumber text,
eventdate text,
eventtime text,
startdayofyear text,
enddayofyear text,
year text,
month text,
day text,
verbatimeventdate text,
habitat text,
highergeography text,
continent text,
countrycode text,
stateprovince text,
county text,
municipality text,
locality text,
verbatimlocality text,
verbatimelevation text,
minimumdistanceabovesurfaceinmeters text,
maximumdistanceabovesurfaceinmeters text,
locationaccordingto text,
decimallatitude double precision,
decimallongitude double precision,
coordinateuncertaintyinmeters text,
coordinateprecision text,
verbatimcoordinatesystem text,
georeferencedby text,
georeferenceprotocol text,
georeferencesources text,
georeferenceverificationstatus text,
georeferenceremarks text,
identificationid text,
identificationqualifier text,
identifiedby text,
dateidentified text,
identificationverificationstatus text,
identificationremarks text,
taxonid text,
higherclassification text,
kingdom text,
phylum text,
class text,
taxonomic_order text,
familyx text,
genus text,
specificepithet text,
infraspecificepithet text,
taxonrank text,
verbatimtaxonrank text,
vernacularname text,
nomenclaturalcode text,
taxonomicstatus text,
datasetkey text,
publishingcountry text,
lastinterpreted text,
elevation text,
elevationaccuracy text,
issue text,
mediatype text,
hascoordinate text,
hasgeospatialissues text,
taxonkey bigint,
acceptedtaxonkey bigint,
kingdomkey integer,
phylumkey text,
classkey text,
orderkey text,
familykey text,
genuskey text,
specieskey text,
species text,
genericname text,
acceptedscientificname text,
verbatimscientificname text,
protocol text,
lastparsed text,
lastcrawled text,
repatriated text,
level0gid text,
level0name text,
level1gid text,
level1name text,
level2gid text,
level2name text,
scientificname text,
nameoriginal text,
nameadjudicated text,
reason text,
comment text,
nameid text,
authoradjudicated text,
status text,
nameaccepted text,
authoraccepted text,
familyy text,
taxonsource text,
level text,
category text,
habit text,
native text,
nonnative text,
list text,
rankstate text,
rankglobal text,
original_decimallatitude double precision,
original_decimallongitude double precision,
observation_office_note text,
location_in_chugach_state_park boolean DEFAULT true,
high_quality_location_data boolean DEFAULT false,
iucnredlistcategory text,
serial integer NOT NULL DEFAULT nextval('gbif_csp_20220320_clipped_foa_taxonomy_serial_seq'::regclass),
    CONSTRAINT gbif_csp_20220320_clipped_foa_taxonomy_pkey PRIMARY KEY (serial),
    CONSTRAINT gbif_csp_20210211_clipped_foa_taxonomy_gbifid_ukey_two UNIQUE (gbifid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.gbif_csp_20220320_clipped_foa_taxonomy
    OWNER to aaronwells;

COMMENT ON TABLE public.gbif_csp_20220320_clipped_foa_taxonomy
    IS 'List of 2021 GBIF vascular plant, bryophyte, and fungi observations clipped to the Chugach State Park boundary with the new Flora of Alaska names assigned. Exported from GBIF on 20210320.';

COMMENT ON COLUMN public.gbif_csp_20220320_clipped_foa_taxonomy.location_in_chugach_state_park
    IS 'Is the location within the boundary of Chugach State Park, true or false.';

COMMENT ON COLUMN public.gbif_csp_20220320_clipped_foa_taxonomy.high_quality_location_data
    IS 'Is the location information for an observation high quality, true or false.';