-- Table: public.gbif_csp_20210211_clipped_foa_taxonomy

-- DROP TABLE public.gbif_csp_20210211_clipped_foa_taxonomy;

CREATE TABLE public.gbif_csp_20210211_clipped_foa_taxonomy
(
    objectid integer,
gbifid bigint,
accessrights text,
bibliographiccitation text,
identifier text,
language text,
license text,
modified text,
	reference text,
rights text,
rightsholder text,
type text,
institutionid text,
collectionid text,
datasetid text,
institutioncode text,
collectioncode text,
datasetname text,
ownerinstitutioncode text,
basisofrecord text,
informationwithheld text,
dynamicproperties text,
occurrenceid text,
catalognumber text,
recordnumber text,
recordedby text,
individualcount text,
reproductivecondition text,
occurrencestatus text,
preparations text,
disposition text,
associatedreferences text,
associatedtaxa text,
othercatalognumbers text,
occurrenceremarks text,
organismid text,
previousidentifications text,
materialsampleid text,
eventid text,
fieldnumber text,
eventdate text,
eventtime text,
startdayofyear text,
enddayofyear text,
year text,
month text,
day text,
verbatimeventdate text,
habitat text,
highergeography text,
continent text,
countrycode text,
stateprovince text,
county text,
municipality text,
locality text,
verbatimlocality text,
verbatimelevation text,
minimumdistanceabovesurfaceinmeters text,
maximumdistanceabovesurfaceinmeters text,
locationaccordingto text,
decimallatitude double precision,
decimallongitude double precision,
coordinateuncertaintyinmeters text,
coordinateprecision text,
verbatimcoordinatesystem text,
georeferencedby text,
georeferenceprotocol text,
georeferencesources text,
georeferenceverificationstatus text,
georeferenceremarks text,
identificationid text,
identificationqualifier text,
identifiedby text,
dateidentified text,
identificationverificationstatus text,
identificationremarks text,
taxonid text,
higherclassification text,
kingdom text,
phylum text,
class text,
taxonomic_order text,
familyx text,
genus text,
specificepithet text,
infraspecificepithet text,
taxonrank text,
verbatimtaxonrank text,
vernacularname text,
nomenclaturalcode text,
taxonomicstatus text,
datasetkey text,
publishingcountry text,
lastinterpreted text,
elevation text,
elevationaccuracy text,
issue text,
mediatype text,
hascoordinate text,
hasgeospatialissues text,
taxonkey bigint,
acceptedtaxonkey bigint,
kingdomkey integer,
phylumkey text,
classkey text,
orderkey text,
familykey text,
genuskey text,
specieskey text,
species text,
genericname text,
acceptedscientificname text,
verbatimscientificname text,
protocol text,
lastparsed text,
lastcrawled text,
repatriated text,
level0gid text,
level0name text,
level1gid text,
level1name text,
level2gid text,
level2name text,
scientificname text,
nameoriginal text,
nameadjudicated text,
reason text,
comment text,
nameid text,
authoradjudicated text,
status text,
nameaccepted text,
authoraccepted text,
familyy text,
taxonsource text,
level text,
category text,
habit text,
native text,
nonnative text,
list text,
rankstate text,
rankglobal text
);

ALTER TABLE public.gbif_csp_20210211_clipped_foa_taxonomy
    OWNER to aaronwells;

COMMENT ON TABLE public.gbif_csp_20210211_clipped_foa_taxonomy
    IS 'List of GBIF vascular plant, bryophyte, and fungi observations clipped to the Chugach State Park boundary with the new Flora of Alaska names assigned. Exported from GBIF on 20210211.';